development:
  adapter:  postgresql
  database: simple_ci_dev
  username: dev
  password: dev
  host:     localhost

test:
  adapter:  postgresql
  database: simple_ci_test
  username: dev
  password: dev
  host:     localhost

production:
  adapter:  postgresql
  database: simple_ci_prod
