development:
  adapter:  postgresql
  database: simple_ci_dev
  username: oscardev
  password: 123456
  host:     localhost

test:
  adapter:  postgresql
  database: simple_ci_test
  username: oscardev
  password: 123456
  host:     localhost

production:
  adapter:  postgresql
  database: simple_ci_prod
