development:
  adapter:  postgresql
  database: simple_ci_dev
  user:     dev
  password: dev

test:
  adapter:  postgresql
  database: simple_ci_test
  user:     dev
  password: dev

production:
  adapter:  postgresql
  database: simple_ci_prod
  user:     dev
  password: dev
